# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: '0/5 * * * *'
    

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - shell: bash
        env: 
          api_key: ${{ secrets.shodan_api_key }}
      # Runs a single command using key
        name: Run a key
        run: |
          echo $api_key
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Hello, ws!"
      
      #runs something random
      - name: Runs random
        run: |
          echo "shit!"
          echo "easy to use"
          echo $api_key
      

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
        
  
